### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by abhishekgoyal-a11y** [jazzband/django-embed-video#152]
Showing error

Backend wasn't recognised (``)
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\embed_video\templatetags\embed_video_tags.py", line 117, in render
    return self.embed(url, size, context=context, **options)
  File "C:\Python38\lib\site-packages\embed_video\templatetags\embed_video_tags.py", line 196, in embed
    backend = cls.get_backend(url, context=context, **options)
  File "C:\Python38\lib\site-packages\embed_video\templatetags\embed_video_tags.py", line 174, in get_backend
    else detect_backend(str(backend_or_url))
  File "C:\Python38\lib\site-packages\embed_video\backends.py", line 64, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException

**Comment by Lifechess** [comment]
I'm curious about this issue too, i got the same error?

**Comment by mgrdcm** [comment]
@abhishekgoyal-a11y and @Lifechess can you include the URL that you're trying to load via `django-embed-video` please?

**Comment by Lifechess** [comment]
https://www.youtube.com/watch?v=CYAHqNWLiq0

**Comment by paulr2021** [comment]
Have installed version 1.4.1 today, also getting same error as above.

`[07/Jan/2022 16:21:06] "GET / HTTP/1.1" 200 3615
Backend wasn't recognised (``)
Traceback (most recent call last):
  File "/Users/paulr/PycharmProjects/django-cms/venv/lib/python3.9/site-packages/embed_video/templatetags/embed_video_tags.py", line 118, in render
    backend = self.get_backend(url, context=context, **options)
  File "/Users/paulr/PycharmProjects/django-cms/venv/lib/python3.9/site-packages/embed_video/templatetags/embed_video_tags.py", line 174, in get_backend
    else detect_backend(str(backend_or_url))
  File "/Users/paulr/PycharmProjects/django-cms/venv/lib/python3.9/site-packages/embed_video/backends.py", line 64, in detect_backend
    raise UnknownBackendException
embed_video.backends.UnknownBackendException`
